// Autogenerated from Pigeon (v26.1.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsNfcWalletSuppressionPigeon(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsNfcWalletSuppressionPigeon(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsNfcWalletSuppressionPigeon(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashNfcWalletSuppressionPigeon(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashNfcWalletSuppressionPigeon(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashNfcWalletSuppressionPigeon(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Status result from suppression operations
enum SuppressionStatusCode: Int {
  /// Suppression is active
  case suppressed = 0
  /// Suppression is not active
  case notSuppressed = 1
  /// Device or OS does not support suppression
  case notSupported = 2
  /// Device is already presenting passes
  case alreadyPresenting = 3
  /// User cancelled the suppression request
  case cancelled = 4
  /// User or system denied the suppression request
  case denied = 5
  /// NFC is not available (disabled, missing hardware, etc.)
  case unavailable = 6
  /// Unknown status or error
  case unknown = 7
}

/// Result of a suppression operation with status and optional message
///
/// Generated class from Pigeon that represents data sent in messages.
struct SuppressionResult: Hashable {
  /// The status of the suppression operation
  var status: SuppressionStatusCode
  /// Optional human-readable message providing additional context
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SuppressionResult? {
    let status = pigeonVar_list[0] as! SuppressionStatusCode
    let message: String? = nilOrValue(pigeonVar_list[1])

    return SuppressionResult(
      status: status,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      message,
    ]
  }
  static func == (lhs: SuppressionResult, rhs: SuppressionResult) -> Bool {
    return deepEqualsNfcWalletSuppressionPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashNfcWalletSuppressionPigeon(value: toList(), hasher: &hasher)
  }
}

private class NfcWalletSuppressionPigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SuppressionStatusCode(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return SuppressionResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class NfcWalletSuppressionPigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SuppressionStatusCode {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? SuppressionResult {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class NfcWalletSuppressionPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NfcWalletSuppressionPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NfcWalletSuppressionPigeonPigeonCodecWriter(data: data)
  }
}

class NfcWalletSuppressionPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NfcWalletSuppressionPigeonPigeonCodec(readerWriter: NfcWalletSuppressionPigeonPigeonCodecReaderWriter())
}


/// Host API for NFC wallet suppression
///
/// This API allows Flutter apps to suppress the automatic presentation
/// of NFC wallet apps (Apple Wallet, Google Pay, etc.) during NFC operations.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NfcWalletSuppressionApi {
  /// Request suppression of the NFC wallet
  ///
  /// Returns a [SuppressionResult] indicating the outcome of the request.
  /// On iOS, this uses PassKit's automatic pass presentation suppression.
  /// On Android, this uses NFC reader mode to prevent wallet apps.
  func requestSuppression(completion: @escaping (Result<SuppressionResult, Error>) -> Void)
  /// Release suppression of the NFC wallet
  ///
  /// Returns a [SuppressionResult] indicating the outcome of the release.
  /// Should be called when NFC operations are complete to restore normal behavior.
  func releaseSuppression(completion: @escaping (Result<SuppressionResult, Error>) -> Void)
  /// Check if NFC wallet is currently suppressed
  ///
  /// Returns true if suppression is currently active, false otherwise.
  func isSuppressed(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Check if device supports NFC wallet suppression
  ///
  /// Returns true if the device has the necessary hardware and OS support,
  /// false otherwise. Should be called before attempting to use suppression.
  func isSupported(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NfcWalletSuppressionApiSetup {
  static var codec: FlutterStandardMessageCodec { NfcWalletSuppressionPigeonPigeonCodec.shared }
  /// Sets up an instance of `NfcWalletSuppressionApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NfcWalletSuppressionApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Request suppression of the NFC wallet
    ///
    /// Returns a [SuppressionResult] indicating the outcome of the request.
    /// On iOS, this uses PassKit's automatic pass presentation suppression.
    /// On Android, this uses NFC reader mode to prevent wallet apps.
    let requestSuppressionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nfc_wallet_suppression.NfcWalletSuppressionApi.requestSuppression\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestSuppressionChannel.setMessageHandler { _, reply in
        api.requestSuppression { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestSuppressionChannel.setMessageHandler(nil)
    }
    /// Release suppression of the NFC wallet
    ///
    /// Returns a [SuppressionResult] indicating the outcome of the release.
    /// Should be called when NFC operations are complete to restore normal behavior.
    let releaseSuppressionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nfc_wallet_suppression.NfcWalletSuppressionApi.releaseSuppression\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseSuppressionChannel.setMessageHandler { _, reply in
        api.releaseSuppression { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      releaseSuppressionChannel.setMessageHandler(nil)
    }
    /// Check if NFC wallet is currently suppressed
    ///
    /// Returns true if suppression is currently active, false otherwise.
    let isSuppressedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nfc_wallet_suppression.NfcWalletSuppressionApi.isSuppressed\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSuppressedChannel.setMessageHandler { _, reply in
        api.isSuppressed { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isSuppressedChannel.setMessageHandler(nil)
    }
    /// Check if device supports NFC wallet suppression
    ///
    /// Returns true if the device has the necessary hardware and OS support,
    /// false otherwise. Should be called before attempting to use suppression.
    let isSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nfc_wallet_suppression.NfcWalletSuppressionApi.isSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSupportedChannel.setMessageHandler { _, reply in
        api.isSupported { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isSupportedChannel.setMessageHandler(nil)
    }
  }
}
