// Autogenerated from Pigeon (v26.1.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.teklund.nfc_wallet_suppression

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NfcWalletSuppressionPigeonPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Status result from suppression operations */
enum class SuppressionStatusCode(val raw: Int) {
  /** Suppression is active */
  SUPPRESSED(0),
  /** Suppression is not active */
  NOT_SUPPRESSED(1),
  /** Device or OS does not support suppression */
  NOT_SUPPORTED(2),
  /** Device is already presenting passes */
  ALREADY_PRESENTING(3),
  /** User cancelled the suppression request */
  CANCELLED(4),
  /** User or system denied the suppression request */
  DENIED(5),
  /** NFC is not available (disabled, missing hardware, etc.) */
  UNAVAILABLE(6),
  /** Unknown status or error */
  UNKNOWN(7);

  companion object {
    fun ofRaw(raw: Int): SuppressionStatusCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Result of a suppression operation with status and optional message
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SuppressionResult (
  /** The status of the suppression operation */
  val status: SuppressionStatusCode,
  /** Optional human-readable message providing additional context */
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SuppressionResult {
      val status = pigeonVar_list[0] as SuppressionStatusCode
      val message = pigeonVar_list[1] as String?
      return SuppressionResult(status, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SuppressionResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return NfcWalletSuppressionPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class NfcWalletSuppressionPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SuppressionStatusCode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SuppressionResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SuppressionStatusCode -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is SuppressionResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API for NFC wallet suppression
 *
 * This API allows Flutter apps to suppress the automatic presentation
 * of NFC wallet apps (Apple Wallet, Google Pay, etc.) during NFC operations.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface NfcWalletSuppressionApi {
  /**
   * Request suppression of the NFC wallet
   *
   * Returns a [SuppressionResult] indicating the outcome of the request.
   * On iOS, this uses PassKit's automatic pass presentation suppression.
   * On Android, this uses NFC reader mode to prevent wallet apps.
   */
  fun requestSuppression(callback: (Result<SuppressionResult>) -> Unit)
  /**
   * Release suppression of the NFC wallet
   *
   * Returns a [SuppressionResult] indicating the outcome of the release.
   * Should be called when NFC operations are complete to restore normal behavior.
   */
  fun releaseSuppression(callback: (Result<SuppressionResult>) -> Unit)
  /**
   * Check if NFC wallet is currently suppressed
   *
   * Returns true if suppression is currently active, false otherwise.
   */
  fun isSuppressed(callback: (Result<Boolean>) -> Unit)
  /**
   * Check if device supports NFC wallet suppression
   *
   * Returns true if the device has the necessary hardware and OS support,
   * false otherwise. Should be called before attempting to use suppression.
   */
  fun isSupported(callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by NfcWalletSuppressionApi. */
    val codec: MessageCodec<Any?> by lazy {
      NfcWalletSuppressionPigeonPigeonCodec()
    }
    /** Sets up an instance of `NfcWalletSuppressionApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NfcWalletSuppressionApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nfc_wallet_suppression.NfcWalletSuppressionApi.requestSuppression$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestSuppression{ result: Result<SuppressionResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NfcWalletSuppressionPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NfcWalletSuppressionPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nfc_wallet_suppression.NfcWalletSuppressionApi.releaseSuppression$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.releaseSuppression{ result: Result<SuppressionResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NfcWalletSuppressionPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NfcWalletSuppressionPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nfc_wallet_suppression.NfcWalletSuppressionApi.isSuppressed$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isSuppressed{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NfcWalletSuppressionPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NfcWalletSuppressionPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nfc_wallet_suppression.NfcWalletSuppressionApi.isSupported$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isSupported{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NfcWalletSuppressionPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NfcWalletSuppressionPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
