// Autogenerated from Pigeon (v26.1.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every((MapEntry<Object?, Object?> entry) =>
            (b as Map<Object?, Object?>).containsKey(entry.key) &&
            _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}

/// Status result from suppression operations
enum SuppressionStatusCode {
  /// Suppression is active
  suppressed,

  /// Suppression is not active
  notSuppressed,

  /// Device or OS does not support suppression
  notSupported,

  /// Device is already presenting passes
  alreadyPresenting,

  /// User cancelled the suppression request
  cancelled,

  /// User or system denied the suppression request
  denied,

  /// NFC is not available (disabled, missing hardware, etc.)
  unavailable,

  /// Unknown status or error
  unknown,
}

/// Result of a suppression operation with status and optional message
class SuppressionResult {
  SuppressionResult({
    required this.status,
    this.message,
  });

  /// The status of the suppression operation
  SuppressionStatusCode status;

  /// Optional human-readable message providing additional context
  String? message;

  List<Object?> _toList() {
    return <Object?>[
      status,
      message,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SuppressionResult decode(Object result) {
    result as List<Object?>;
    return SuppressionResult(
      status: result[0]! as SuppressionStatusCode,
      message: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SuppressionResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is SuppressionStatusCode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is SuppressionResult) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : SuppressionStatusCode.values[value];
      case 130:
        return SuppressionResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API for NFC wallet suppression
///
/// This API allows Flutter apps to suppress the automatic presentation
/// of NFC wallet apps (Apple Wallet, Google Pay, etc.) during NFC operations.
class NfcWalletSuppressionApi {
  /// Constructor for [NfcWalletSuppressionApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NfcWalletSuppressionApi(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Request suppression of the NFC wallet
  ///
  /// Returns a [SuppressionResult] indicating the outcome of the request.
  /// On iOS, this uses PassKit's automatic pass presentation suppression.
  /// On Android, this uses NFC reader mode to prevent wallet apps.
  Future<SuppressionResult> requestSuppression() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nfc_wallet_suppression.NfcWalletSuppressionApi.requestSuppression$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as SuppressionResult?)!;
    }
  }

  /// Release suppression of the NFC wallet
  ///
  /// Returns a [SuppressionResult] indicating the outcome of the release.
  /// Should be called when NFC operations are complete to restore normal behavior.
  Future<SuppressionResult> releaseSuppression() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nfc_wallet_suppression.NfcWalletSuppressionApi.releaseSuppression$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as SuppressionResult?)!;
    }
  }

  /// Check if NFC wallet is currently suppressed
  ///
  /// Returns true if suppression is currently active, false otherwise.
  Future<bool> isSuppressed() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nfc_wallet_suppression.NfcWalletSuppressionApi.isSuppressed$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Check if device supports NFC wallet suppression
  ///
  /// Returns true if the device has the necessary hardware and OS support,
  /// false otherwise. Should be called before attempting to use suppression.
  Future<bool> isSupported() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.nfc_wallet_suppression.NfcWalletSuppressionApi.isSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }
}
